#mongo users automation
#password: "{{ lookup('file', '/etc/ansible/pass.txt') }}"

---

- name: generate password using pwgen command on local and creating mongo user..
  hosts: remote
  any_errors_fatal: True
  vars_files:
    - group_vars/main.yml

  tasks:
  - shell: pwgen -s 15 1
    register: pass1
    connection: local

  - shell: pwgen -s 15 1
    register: pass2
    delegate_to: 127.0.0.1

  - debug: msg="pass1={{pass1.stdout}} and pass2={{pass2.stdout}}  "]

  - stat: path=/etc/init.d/"{{service_name}}"
    register: service_exists
  - service: name="{{ service_name }}" state=running
    when: service_exists.stat.exists

  - debug: msg="creating mongoadmin user....."
  - mongodb_user: login_user="{{mongo_auth_user}}" login_password="{{mongo_auth_pass}}" name="{{mongo_admin_user}}" password="{{pass1.stdout}}" database="{{mongo_admin_db}}" state=present
  - debug: msg="admin username is {{mongo_admin_user}}"

  - debug: msg="creating another user......"
  - mongodb_user: 
      login_user: "{{mongo_auth_user}}"
      login_password: "{{mongo_auth_pass}}"
      database: "{{db_name}}"
      user: "{{user_name}}"
      password: "{{pass2.stdout}}"
      state: present
      roles: "readWrite"
  - debug: msg="{{user_name}} is created in {{db_name}}"

  - debug: msg="deleting temp_user........."
  - mongodb_user: login_user="{{mongo_auth_user}}" login_password="{{mongo_auth_pass}}" database="{{mongo_admin_db}}" name="{{mongo_auth_user}}" state=absent
  
  - debug: msg="temp_user is deleted"
    
  - debug: msg="password for admin={{pass1.stdout}} and password for your dev db={{pass2.stdout}}  "
